services:
  postgres:
    image: postgres:16-alpine
    container_name: saucerank-db
    environment:
      POSTGRES_DB: saucerank
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: DAniel10
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    build: ./backend
    container_name: saucerank-api
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/saucerank
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: DAniel10
    ports:
      - "8080:8080"

  frontend:
    build: ./frontend
    container_name: saucerank-web
    depends_on:
      - backend
    ports:
      - "5173:80"
    environment:
      VITE_API_URL: http://localhost:8080

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: saucerank-pgadmin
    depends_on:
      - postgres
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@saucerank.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - "5050:80"
    volumes:
      - pgadmin-data:/var/lib/pgadmin

volumes:
  pgdata:
  pgadmin-data:
