server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/saucerank
    username: postgres
    password: DAniel10
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    defer-datasource-initialization: true
  sql:
    init:
      mode: always

app:
  jwt:
    secret: "SauceRankSecretKey2024EladioCarrionSuperSecureJWTKey123456789"
    expiration-ms: 86400000
